source 'http://rubygems.org'

gem 'sinatra'
gem 'haml'
gem 'savon'
gem 'mongoid', '~> 2.1'
gem 'mongoid_auto_inc'
gem 'bson_ext', '~> 1.3'
gem 'diff-lcs', '~> 1.1.2', :require => 'diff/lcs'
gem 'pusher'